package InformationApp;


/**
* InformationApp/Information.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Information.idl
* Thursday, May 7, 2015 1:57:56 PM BDT
*/

public interface Information extends InformationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Information
