package InformationApp;

/**
* InformationApp/InformationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Information.idl
* Thursday, May 7, 2015 1:57:56 PM BDT
*/

public final class InformationHolder implements org.omg.CORBA.portable.Streamable
{
  public InformationApp.Information value = null;

  public InformationHolder ()
  {
  }

  public InformationHolder (InformationApp.Information initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InformationApp.InformationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InformationApp.InformationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InformationApp.InformationHelper.type ();
  }

}
