package InformationApp;


/**
* InformationApp/InformationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Information.idl
* Thursday, May 7, 2015 1:57:56 PM BDT
*/

public interface InformationOperations 
{
  String info (String name);
  void shutdown ();
} // interface InformationOperations
